-- =================================================================
-- 1. SUPPRESSION DES TABLES EXISTANTES (REMISE A ZERO)
-- =================================================================
DROP TABLE glpi_profilerights CASCADE CONSTRAINTS;
DROP TABLE glpi_datacenters CASCADE CONSTRAINTS;
DROP TABLE glpi_ipaddresses CASCADE CONSTRAINTS;
DROP TABLE glpi_printers CASCADE CONSTRAINTS;
DROP TABLE glpi_computers CASCADE CONSTRAINTS;
DROP TABLE glpi_networks CASCADE CONSTRAINTS;
DROP TABLE glpi_profiles_users CASCADE CONSTRAINTS;
DROP TABLE glpi_profiles CASCADE CONSTRAINTS;
DROP TABLE glpi_users CASCADE CONSTRAINTS;
DROP TABLE glpi_locations CASCADE CONSTRAINTS;
DROP TABLE glpi_entities CASCADE CONSTRAINTS;

-- =================================================================
-- 2. CREATION DES TABLES (Syntaxe Oracle)
-- =================================================================

CREATE TABLE glpi_entities (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255),
  entities_id NUMBER DEFAULT 0,
  lvl NUMBER DEFAULT 0 NOT NULL -- Renommé car 'level' est un mot réservé Oracle
);

CREATE TABLE glpi_locations (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entities_id NUMBER DEFAULT 0 NOT NULL,
  name VARCHAR2(255),
  locations_id NUMBER DEFAULT 0 NOT NULL,
  lvl NUMBER DEFAULT 0 NOT NULL, -- Renommé car 'level' est un mot réservé Oracle
  address VARCHAR2(4000),
  postcode VARCHAR2(255),
  town VARCHAR2(255)
);

CREATE TABLE glpi_users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255),
  realname VARCHAR2(255),
  firstname VARCHAR2(255),
  locations_id NUMBER DEFAULT 0 NOT NULL,
  is_active NUMBER(1) DEFAULT 1 NOT NULL,
  entities_id NUMBER DEFAULT 0
);

CREATE TABLE glpi_profiles (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255),
  interface VARCHAR2(255) DEFAULT 'helpdesk'
);

CREATE TABLE glpi_profiles_users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id NUMBER DEFAULT 0 NOT NULL,
  profiles_id NUMBER DEFAULT 0 NOT NULL,
  entities_id NUMBER DEFAULT 0 NOT NULL,
  is_recursive NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE glpi_networks (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255)
);

CREATE TABLE glpi_computers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entities_id NUMBER DEFAULT 0 NOT NULL,
  name VARCHAR2(255),
  serial VARCHAR2(255),
  users_id_tech NUMBER DEFAULT 0 NOT NULL,
  locations_id NUMBER DEFAULT 0 NOT NULL,
  networks_id NUMBER DEFAULT 0 NOT NULL,
  users_id NUMBER DEFAULT 0 NOT NULL,
  states_id NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE glpi_printers (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entities_id NUMBER DEFAULT 0 NOT NULL,
  name VARCHAR2(255),
  serial VARCHAR2(255),
  users_id_tech NUMBER DEFAULT 0 NOT NULL,
  locations_id NUMBER DEFAULT 0 NOT NULL,
  networks_id NUMBER DEFAULT 0 NOT NULL,
  users_id NUMBER DEFAULT 0 NOT NULL,
  states_id NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE glpi_ipaddresses (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entities_id NUMBER DEFAULT 0 NOT NULL,
  items_id NUMBER DEFAULT 0 NOT NULL,
  itemtype VARCHAR2(100) NOT NULL,
  name VARCHAR2(255),
  mainitems_id NUMBER DEFAULT 0 NOT NULL,
  mainitemtype VARCHAR2(255)
);

CREATE TABLE glpi_datacenters (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255),
  entities_id NUMBER DEFAULT 0 NOT NULL,
  locations_id NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE glpi_profilerights (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profiles_id NUMBER DEFAULT 0 NOT NULL,
  name VARCHAR2(255),
  rights NUMBER DEFAULT 0 NOT NULL
);

-- =================================================================
-- 3. CREATION DES INDEX (Noms uniques pour Oracle)
-- =================================================================

-- Index Uniques
CREATE UNIQUE INDEX uk_ent_id_name ON glpi_entities (entities_id, name);
CREATE UNIQUE INDEX uk_loc_ent_loc_name ON glpi_locations (entities_id, locations_id, name);
CREATE UNIQUE INDEX uk_profrights_prof_name ON glpi_profilerights (profiles_id, name);

-- Index glpi_entities
CREATE INDEX idx_ent_lvl ON glpi_entities (lvl);

-- Index glpi_locations
CREATE INDEX idx_loc_loc_id ON glpi_locations (locations_id);
CREATE INDEX idx_loc_name ON glpi_locations (name);
CREATE INDEX idx_loc_lvl ON glpi_locations (lvl);

-- Index glpi_users
CREATE INDEX idx_usr_realname ON glpi_users (realname);
CREATE INDEX idx_usr_ent_id ON glpi_users (entities_id);
CREATE INDEX idx_usr_loc_id ON glpi_users (locations_id);
CREATE INDEX idx_usr_is_active ON glpi_users (is_active);

-- Index glpi_profiles
CREATE INDEX idx_prof_name ON glpi_profiles (name);

-- Index glpi_profiles_users
CREATE INDEX idx_pu_ent_id ON glpi_profiles_users (entities_id);
CREATE INDEX idx_pu_prof_id ON glpi_profiles_users (profiles_id);
CREATE INDEX idx_pu_usr_id ON glpi_profiles_users (users_id);

-- Index glpi_networks
CREATE INDEX idx_net_name ON glpi_networks (name);

-- Index glpi_computers
CREATE INDEX idx_comp_name ON glpi_computers (name);
CREATE INDEX idx_comp_ent_id ON glpi_computers (entities_id);
CREATE INDEX idx_comp_serial ON glpi_computers (serial);
CREATE INDEX idx_comp_loc_id ON glpi_computers (locations_id);
CREATE INDEX idx_comp_net_id ON glpi_computers (networks_id);

-- Index glpi_printers
CREATE INDEX idx_print_name ON glpi_printers (name);
CREATE INDEX idx_print_ent_id ON glpi_printers (entities_id);
CREATE INDEX idx_print_serial ON glpi_printers (serial);
CREATE INDEX idx_print_loc_id ON glpi_printers (locations_id);
CREATE INDEX idx_print_net_id ON glpi_printers (networks_id);

-- Index glpi_ipaddresses
CREATE INDEX idx_ip_name ON glpi_ipaddresses (name);
CREATE INDEX idx_ip_ent_id ON glpi_ipaddresses (entities_id);
CREATE INDEX idx_ip_item ON glpi_ipaddresses (itemtype, items_id);
CREATE INDEX idx_ip_mainitem ON glpi_ipaddresses (mainitemtype, mainitems_id);

-- Index glpi_datacenters
CREATE INDEX idx_dc_name ON glpi_datacenters (name);
CREATE INDEX idx_dc_ent_id ON glpi_datacenters (entities_id);
CREATE INDEX idx_dc_loc_id ON glpi_datacenters (locations_id);

-- Index glpi_profilerights
CREATE INDEX idx_profright_name ON glpi_profilerights (name);


-- =================================================================
-- 4. AJOUT DES CLES ETRANGERES (L'optimisation attendue par ton prof)
-- =================================================================

ALTER TABLE glpi_entities ADD CONSTRAINT fk_ent_parent FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);

ALTER TABLE glpi_locations ADD CONSTRAINT fk_loc_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_locations ADD CONSTRAINT fk_loc_parent FOREIGN KEY (locations_id) REFERENCES glpi_locations(id);

ALTER TABLE glpi_users ADD CONSTRAINT fk_usr_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_users ADD CONSTRAINT fk_usr_location FOREIGN KEY (locations_id) REFERENCES glpi_locations(id);

ALTER TABLE glpi_profiles_users ADD CONSTRAINT fk_pu_user FOREIGN KEY (users_id) REFERENCES glpi_users(id);
ALTER TABLE glpi_profiles_users ADD CONSTRAINT fk_pu_profile FOREIGN KEY (profiles_id) REFERENCES glpi_profiles(id);
ALTER TABLE glpi_profiles_users ADD CONSTRAINT fk_pu_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);

ALTER TABLE glpi_computers ADD CONSTRAINT fk_comp_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_computers ADD CONSTRAINT fk_comp_location FOREIGN KEY (locations_id) REFERENCES glpi_locations(id);
ALTER TABLE glpi_computers ADD CONSTRAINT fk_comp_network FOREIGN KEY (networks_id) REFERENCES glpi_networks(id);
ALTER TABLE glpi_computers ADD CONSTRAINT fk_comp_user FOREIGN KEY (users_id) REFERENCES glpi_users(id);
ALTER TABLE glpi_computers ADD CONSTRAINT fk_comp_tech FOREIGN KEY (users_id_tech) REFERENCES glpi_users(id);

ALTER TABLE glpi_printers ADD CONSTRAINT fk_print_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_printers ADD CONSTRAINT fk_print_location FOREIGN KEY (locations_id) REFERENCES glpi_locations(id);
ALTER TABLE glpi_printers ADD CONSTRAINT fk_print_network FOREIGN KEY (networks_id) REFERENCES glpi_networks(id);
ALTER TABLE glpi_printers ADD CONSTRAINT fk_print_user FOREIGN KEY (users_id) REFERENCES glpi_users(id);

ALTER TABLE glpi_ipaddresses ADD CONSTRAINT fk_ip_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);

ALTER TABLE glpi_datacenters ADD CONSTRAINT fk_dc_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_datacenters ADD CONSTRAINT fk_dc_location FOREIGN KEY (locations_id) REFERENCES glpi_locations(id);

ALTER TABLE glpi_profilerights ADD CONSTRAINT fk_profrights_profile FOREIGN KEY (profiles_id) REFERENCES glpi_profiles(id);
