-- =============================================================================
-- GLPI CY Tech - Schema applicatif (VERSION ULTRA-VIERGE / SANS INDEX)
-- =============================================================================

-- =============================================================================
-- 1. SUPPRESSION DES TABLES EXISTANTES
-- =============================================================================
DROP TABLE glpi_tickets        CASCADE CONSTRAINTS;
DROP TABLE glpi_computers      CASCADE CONSTRAINTS;
DROP TABLE glpi_printers       CASCADE CONSTRAINTS;
DROP TABLE glpi_equipments     CASCADE CONSTRAINTS;
DROP TABLE glpi_profilerights  CASCADE CONSTRAINTS;
DROP TABLE glpi_ipaddresses    CASCADE CONSTRAINTS;
DROP TABLE glpi_networks       CASCADE CONSTRAINTS;
DROP TABLE glpi_profiles_users CASCADE CONSTRAINTS;
DROP TABLE glpi_profiles       CASCADE CONSTRAINTS;
DROP TABLE glpi_users          CASCADE CONSTRAINTS;
DROP TABLE glpi_locations      CASCADE CONSTRAINTS;
DROP TABLE glpi_entities       CASCADE CONSTRAINTS;
DROP TABLE glpi_history        CASCADE CONSTRAINTS;

-- =============================================================================
-- 2. CREATION DES TABLES
-- =============================================================================

CREATE TABLE glpi_entities (
  id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name     VARCHAR2(255),
  address  VARCHAR2(4000),
  postcode VARCHAR2(255),
  town     VARCHAR2(255)
);

INSERT INTO glpi_entities (id, name) VALUES (1, 'CERGY');
INSERT INTO glpi_entities (id, name) VALUES (2, 'PAU');
COMMIT;

CREATE TABLE glpi_locations (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entities_id NUMBER NOT NULL,
  name        VARCHAR2(255),
  lvl         NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT chk_loc_ent CHECK (entities_id IN (1, 2))
);

CREATE TABLE glpi_users (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pseudo       VARCHAR2(255),
  realname     VARCHAR2(255),
  firstname    VARCHAR2(255),
  locations_id NUMBER DEFAULT NULL,
  is_active    NUMBER(1) DEFAULT 1 NOT NULL,
  entities_id  NUMBER NOT NULL,
  CONSTRAINT chk_usr_ent CHECK (entities_id IN (1, 2))
);

CREATE TABLE glpi_profiles (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR2(255),
  interface VARCHAR2(255) DEFAULT 'helpdesk'
);

CREATE TABLE glpi_profiles_users (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id    NUMBER NOT NULL,
  profiles_id NUMBER NOT NULL,
  entities_id NUMBER NOT NULL,
  CONSTRAINT chk_pu_ent CHECK (entities_id IN (1, 2))
);

CREATE TABLE glpi_networks (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(255),
  entities_id NUMBER NOT NULL,
  CONSTRAINT chk_net_ent CHECK (entities_id IN (1, 2))
);

CREATE TABLE glpi_profilerights (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profiles_id NUMBER NOT NULL,
  name        VARCHAR2(255),
  rights      NUMBER DEFAULT 0 NOT NULL
);

CREATE TABLE glpi_ipaddresses (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(255),
  networks_id NUMBER DEFAULT NULL
);

CREATE TABLE glpi_equipments (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR2(255),
  itemtype       VARCHAR2(100) NOT NULL,
  entities_id    NUMBER NOT NULL,
  locations_id   NUMBER DEFAULT NULL,
  ipaddresses_id NUMBER DEFAULT NULL,
  CONSTRAINT chk_equip_ent_id  CHECK (entities_id IN (1, 2)),
  CONSTRAINT chk_equip_itemtype CHECK (itemtype IN ('Computer', 'Printer'))
);

CREATE TABLE glpi_computers (
  id            NUMBER NOT NULL PRIMARY KEY,
  serial        VARCHAR2(255),
  users_id_tech NUMBER DEFAULT NULL,
  users_id      NUMBER DEFAULT NULL,
  states_id     NUMBER DEFAULT NULL,
  CONSTRAINT fk_comp_inherit FOREIGN KEY (id)
    REFERENCES glpi_equipments(id) ON DELETE CASCADE
);

CREATE TABLE glpi_printers (
  id            NUMBER NOT NULL PRIMARY KEY,
  serial        VARCHAR2(255),
  users_id_tech NUMBER DEFAULT NULL,
  users_id      NUMBER DEFAULT NULL,
  states_id     NUMBER DEFAULT NULL,
  CONSTRAINT fk_print_inherit FOREIGN KEY (id)
    REFERENCES glpi_equipments(id) ON DELETE CASCADE
);

CREATE TABLE glpi_tickets (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         VARCHAR2(255),
  content      CLOB,
  date_issue   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status       NUMBER DEFAULT 1 NOT NULL,
  entities_id  NUMBER NOT NULL,
  locations_id NUMBER DEFAULT NULL,
  equipment_id NUMBER DEFAULT NULL,
  users_id     NUMBER DEFAULT NULL,
  CONSTRAINT chk_ticket_ent  CHECK (entities_id IN (1, 2)),
  CONSTRAINT chk_tick_status CHECK (status IN (1, 2, 3, 4, 5))
);

-- =============================================================================
-- 3. CLES ETRANGERES
-- =============================================================================

ALTER TABLE glpi_equipments ADD CONSTRAINT fk_equip_ent FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_equipments ADD CONSTRAINT fk_equip_loc FOREIGN KEY (locations_id) REFERENCES glpi_locations(id);
ALTER TABLE glpi_equipments ADD CONSTRAINT fk_equip_ip FOREIGN KEY (ipaddresses_id) REFERENCES glpi_ipaddresses(id);

ALTER TABLE glpi_computers ADD CONSTRAINT fk_comp_user FOREIGN KEY (users_id) REFERENCES glpi_users(id);
ALTER TABLE glpi_computers ADD CONSTRAINT fk_comp_tech FOREIGN KEY (users_id_tech) REFERENCES glpi_users(id);

ALTER TABLE glpi_printers ADD CONSTRAINT fk_print_user FOREIGN KEY (users_id) REFERENCES glpi_users(id);
ALTER TABLE glpi_printers ADD CONSTRAINT fk_print_tech FOREIGN KEY (users_id_tech) REFERENCES glpi_users(id);

ALTER TABLE glpi_tickets ADD CONSTRAINT fk_tick_equip FOREIGN KEY (equipment_id) REFERENCES glpi_equipments(id);
ALTER TABLE glpi_tickets ADD CONSTRAINT fk_tick_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_tickets ADD CONSTRAINT fk_tick_location FOREIGN KEY (locations_id) REFERENCES glpi_locations(id);
ALTER TABLE glpi_tickets ADD CONSTRAINT fk_tick_user FOREIGN KEY (users_id) REFERENCES glpi_users(id);

ALTER TABLE glpi_ipaddresses ADD CONSTRAINT fk_ip_net FOREIGN KEY (networks_id) REFERENCES glpi_networks(id);
ALTER TABLE glpi_networks ADD CONSTRAINT fk_net_ent FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_locations ADD CONSTRAINT fk_loc_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);

ALTER TABLE glpi_users ADD CONSTRAINT fk_usr_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);
ALTER TABLE glpi_users ADD CONSTRAINT fk_usr_location FOREIGN KEY (locations_id) REFERENCES glpi_locations(id);

ALTER TABLE glpi_profiles_users ADD CONSTRAINT fk_pu_user FOREIGN KEY (users_id) REFERENCES glpi_users(id);
ALTER TABLE glpi_profiles_users ADD CONSTRAINT fk_pu_profile FOREIGN KEY (profiles_id) REFERENCES glpi_profiles(id);
ALTER TABLE glpi_profiles_users ADD CONSTRAINT fk_pu_entity FOREIGN KEY (entities_id) REFERENCES glpi_entities(id);

ALTER TABLE glpi_profilerights ADD CONSTRAINT fk_profrights_profile FOREIGN KEY (profiles_id) REFERENCES glpi_profiles(id);

-- =============================================================================
-- 4. CONTRAINTES CHECK SUPPLEMENTAIRES
-- =============================================================================

ALTER TABLE glpi_computers ADD CONSTRAINT chk_comp_states CHECK (states_id IN (1, 2, 3, 4));
ALTER TABLE glpi_printers ADD CONSTRAINT chk_print_states CHECK (states_id IN (1, 2, 3, 4));
