-- =============================================================================
-- GLPI CY Tech - Schema applicatif
-- Fichier    : schema.sql
-- Connexion  : GLPI_OWNER
-- Dependances: 0infrastructure.sql + owner.sql executes avant
-- Contenu    : DROP / CREATE tables, INSERT entites, index, FK, CHECK, UNIQUE
-- =============================================================================


-- =============================================================================
-- 1. SUPPRESSION DES TABLES EXISTANTES (remise a zero)
-- =============================================================================
-- CASCADE CONSTRAINTS supprime toutes les FK qui referencent la table avant
-- de la supprimer, evitant les erreurs ORA-02449.
-- Ordre : tables filles avant tables meres.

DROP TABLE glpi_tickets        CASCADE CONSTRAINTS;
DROP TABLE glpi_computers      CASCADE CONSTRAINTS;
DROP TABLE glpi_printers       CASCADE CONSTRAINTS;
DROP TABLE glpi_equipments     CASCADE CONSTRAINTS;
DROP TABLE glpi_profilerights  CASCADE CONSTRAINTS;
DROP TABLE glpi_ipaddresses    CASCADE CONSTRAINTS;
DROP TABLE glpi_networks       CASCADE CONSTRAINTS;
DROP TABLE glpi_profiles_users CASCADE CONSTRAINTS;
DROP TABLE glpi_profiles       CASCADE CONSTRAINTS;
DROP TABLE glpi_users          CASCADE CONSTRAINTS;
DROP TABLE glpi_locations      CASCADE CONSTRAINTS;
DROP TABLE glpi_entities       CASCADE CONSTRAINTS;
DROP TABLE glpi_history        CASCADE CONSTRAINTS;


-- =============================================================================
-- 2. CREATION DES TABLES
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 2.1 Referentiels partages -> TS_GLPI_REF
-- Volumetrie faible et stable. Pas de partitionnement necessaire.
-- -----------------------------------------------------------------------------

-- glpi_entities : les deux sites de CY Tech.
CREATE TABLE glpi_entities (
  id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    VARCHAR2(255),
  address VARCHAR2(4000),
  postcode VARCHAR2(255),
  town    VARCHAR2(255)
)
TABLESPACE TS_GLPI_REF;

-- Donnees structurelles : les deux entites doivent exister avant toute
-- insertion dans les autres tables (contraintes CHECK entities_id IN (1,2)).
INSERT INTO glpi_entities (id, name) VALUES (1, 'CERGY');
INSERT INTO glpi_entities (id, name) VALUES (2, 'PAU');
COMMIT;


-- glpi_locations : liste plate de salles / bureaux par site.
-- Partitionnee par site : les salles de Cergy dans TS_GLPI_CERGY,
-- celles de Pau dans TS_GLPI_PAU.
CREATE TABLE glpi_locations (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  entities_id NUMBER NOT NULL,
  name        VARCHAR2(255),
  lvl         NUMBER DEFAULT 0 NOT NULL,
  CONSTRAINT chk_loc_ent CHECK (entities_id IN (1, 2)),
  CONSTRAINT pk_locations PRIMARY KEY (id) USING INDEX TABLESPACE TS_GLPI_INDX
)
PARTITION BY LIST (entities_id) (
  PARTITION p_cergy VALUES (1) TABLESPACE TS_GLPI_CERGY,
  PARTITION p_pau   VALUES (2) TABLESPACE TS_GLPI_PAU
);


-- glpi_users : utilisateurs metier GLPI (admins, techniciens, lambdas).
-- Attention : ce ne sont PAS les comptes Oracle (crees via ajouter_admin /
-- ajouter_technicien dans le scenario). Un utilisateur lambda n a pas de
-- compte Oracle et n apparait pas dans glpi_profiles_users.
CREATE TABLE glpi_users (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pseudo      VARCHAR2(255),
  realname    VARCHAR2(255),
  firstname   VARCHAR2(255),
  locations_id NUMBER DEFAULT NULL,
  is_active   NUMBER(1) DEFAULT 1 NOT NULL,
  entities_id NUMBER NOT NULL,
  CONSTRAINT chk_usr_ent CHECK (entities_id IN (1, 2))
)
TABLESPACE TS_GLPI_REF;


-- glpi_profiles : catalogue des profils GLPI (Administrateur, Technicien...).
CREATE TABLE glpi_profiles (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR2(255),
  interface VARCHAR2(255) DEFAULT 'helpdesk'
)
TABLESPACE TS_GLPI_REF;


-- glpi_profiles_users : liaison utilisateur <-> profil <-> site.
-- Un lambda n a pas de ligne ici. Seuls admins et techniciens y apparaissent.
CREATE TABLE glpi_profiles_users (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  users_id    NUMBER NOT NULL,
  profiles_id NUMBER NOT NULL,
  entities_id NUMBER NOT NULL,
  CONSTRAINT chk_pu_ent CHECK (entities_id IN (1, 2))
)
TABLESPACE TS_GLPI_REF;


-- glpi_networks : reseaux IP par site (un reseau par site dans notre modele).
CREATE TABLE glpi_networks (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(255),
  entities_id NUMBER NOT NULL,
  CONSTRAINT chk_net_ent CHECK (entities_id IN (1, 2))
)
TABLESPACE TS_GLPI_REF;


-- glpi_profilerights : droits metier associes a chaque profil.
-- Utilise pour la vue v_admin_users_par_type et l audit des droits.
CREATE TABLE glpi_profilerights (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profiles_id NUMBER NOT NULL,
  name        VARCHAR2(255),
  rights      NUMBER DEFAULT 0 NOT NULL
)
TABLESPACE TS_GLPI_REF;


-- glpi_ipaddresses : adresses IP des equipements.
-- Non partitionnee : petite table, lookup frequent depuis les jointures.
-- Le lien au site se fait via networks_id -> glpi_networks.entities_id.
CREATE TABLE glpi_ipaddresses (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(255),
  networks_id NUMBER DEFAULT NULL
)
TABLESPACE TS_GLPI_REF;


-- -----------------------------------------------------------------------------
-- 2.2 Tables d actifs partitionnees par site -> TS_GLPI_CERGY / TS_GLPI_PAU
-- PARTITION BY LIST(entities_id) sans DEFAULT : le CHECK (entities_id IN (1,2))
-- bloque toute valeur hors plage avant meme l insertion physique.
-- Benefices : separation physique, partition pruning, preparation BDDR.
-- -----------------------------------------------------------------------------

-- glpi_equipments : table MERE simulant l heritage.
-- Porte les attributs communs de notre choix (nom, type, site, salle, IP).
-- glpi_computers et glpi_printers sont ses tables FILLES.
CREATE TABLE glpi_equipments (
  id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name           VARCHAR2(255),
  itemtype       VARCHAR2(100) NOT NULL,
  entities_id    NUMBER NOT NULL,
  locations_id   NUMBER DEFAULT NULL,
  ipaddresses_id NUMBER DEFAULT NULL,
  CONSTRAINT chk_equip_ent_id  CHECK (entities_id IN (1, 2)),
  CONSTRAINT chk_equip_itemtype CHECK (itemtype IN ('Computer', 'Printer')),
  CONSTRAINT pk_equipments PRIMARY KEY (id) USING INDEX TABLESPACE TS_GLPI_INDX
)
PARTITION BY LIST (entities_id) (
  PARTITION p_cergy VALUES (1) TABLESPACE TS_GLPI_CERGY,
  PARTITION p_pau   VALUES (2) TABLESPACE TS_GLPI_PAU
);


-- glpi_computers : table FILLE de glpi_equipments.
-- PARTITION BY REFERENCE : les partitions suivent automatiquement celles du
-- parent via fk_comp_inherit. Co-location garantie : un PC de Cergy est dans
-- TS_GLPI_CERGY cote equipments ET cote computers.
CREATE TABLE glpi_computers (
  id           NUMBER NOT NULL,
  serial       VARCHAR2(255),
  users_id_tech NUMBER DEFAULT NULL,
  users_id     NUMBER DEFAULT NULL,
  states_id    NUMBER DEFAULT NULL,
  CONSTRAINT pk_computers  PRIMARY KEY (id) USING INDEX TABLESPACE TS_GLPI_INDX,
  CONSTRAINT fk_comp_inherit FOREIGN KEY (id)
    REFERENCES glpi_equipments(id) ON DELETE CASCADE
)
PARTITION BY REFERENCE (fk_comp_inherit);


-- glpi_printers : table FILLE de glpi_equipments, meme schema que computers.
CREATE TABLE glpi_printers (
  id           NUMBER NOT NULL,
  serial       VARCHAR2(255),
  users_id_tech NUMBER DEFAULT NULL,
  users_id     NUMBER DEFAULT NULL,
  states_id    NUMBER DEFAULT NULL,
  CONSTRAINT pk_printers   PRIMARY KEY (id) USING INDEX TABLESPACE TS_GLPI_INDX,
  CONSTRAINT fk_print_inherit FOREIGN KEY (id)
    REFERENCES glpi_equipments(id) ON DELETE CASCADE
)
PARTITION BY REFERENCE (fk_print_inherit);


-- glpi_tickets : partitionnee par site.
-- locations_id conserve : un ticket peut referencer la salle ou le probleme
-- a ete signale (utile pour v_admin_tickets_en_retard).
CREATE TABLE glpi_tickets (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY,
  name         VARCHAR2(255),
  content      CLOB,
  date_issue   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status       NUMBER DEFAULT 1 NOT NULL,
  entities_id  NUMBER NOT NULL,
  locations_id NUMBER DEFAULT NULL,
  equipment_id NUMBER DEFAULT NULL,
  users_id     NUMBER DEFAULT NULL,
  CONSTRAINT chk_ticket_ent  CHECK (entities_id IN (1, 2)),
  CONSTRAINT chk_tick_status CHECK (status IN (1, 2, 3, 4, 5)),
  CONSTRAINT pk_tickets PRIMARY KEY (id) USING INDEX TABLESPACE TS_GLPI_INDX
)
PARTITION BY LIST (entities_id) (
  PARTITION p_cergy VALUES (1) TABLESPACE TS_GLPI_CERGY,
  PARTITION p_pau   VALUES (2) TABLESPACE TS_GLPI_PAU
);


-- =============================================================================
-- 3. INDEX SECONDAIRES
-- =============================================================================
-- Tous dans TS_GLPI_INDX (separation data / index -> pas de contention IO).
-- Tables partitionnees -> index LOCAL (un sous-index par partition,
-- profite du partition pruning).

-- ---- Index uniques ----------------------------------------------------------
CREATE UNIQUE INDEX uk_ent_name
  ON glpi_entities (name)
  TABLESPACE TS_GLPI_INDX;

-- locations : unicite nom dans un site (plus de locations_id dans la cle)
CREATE UNIQUE INDEX uk_loc_ent_name
  ON glpi_locations (entities_id, name)
  LOCAL TABLESPACE TS_GLPI_INDX;

CREATE UNIQUE INDEX uk_profrights_prof_name
  ON glpi_profilerights (profiles_id, name)
  TABLESPACE TS_GLPI_INDX;

-- Unicite des numeros de serie (par table fille, pas globalement)
CREATE UNIQUE INDEX uk_comp_serial  ON glpi_computers (serial) TABLESPACE TS_GLPI_INDX;
CREATE UNIQUE INDEX uk_print_serial ON glpi_printers  (serial) TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_tickets (partitionnee -> LOCAL) -----------------------------
CREATE INDEX idx_tick_ent_id   ON glpi_tickets (entities_id)  LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_tick_users_id ON glpi_tickets (users_id)     LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_tick_status   ON glpi_tickets (status)       LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_tick_loc_id   ON glpi_tickets (locations_id) LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_tick_equip_id ON glpi_tickets (equipment_id) LOCAL TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_locations (partitionnee -> LOCAL) ---------------------------
CREATE INDEX idx_loc_name ON glpi_locations (name) LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_loc_lvl  ON glpi_locations (lvl)  LOCAL TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_users -------------------------------------------------------
CREATE INDEX idx_usr_realname  ON glpi_users (realname)      TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_usr_ent_id    ON glpi_users (entities_id)   TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_usr_loc_id    ON glpi_users (locations_id)  TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_usr_is_active ON glpi_users (is_active)     TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_usr_pseudo    ON glpi_users (pseudo)        TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_profiles ----------------------------------------------------
CREATE INDEX idx_prof_name ON glpi_profiles (name) TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_profiles_users ----------------------------------------------
CREATE INDEX idx_pu_ent_id  ON glpi_profiles_users (entities_id) TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_pu_prof_id ON glpi_profiles_users (profiles_id) TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_pu_usr_id  ON glpi_profiles_users (users_id)    TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_networks ----------------------------------------------------
CREATE INDEX idx_net_name   ON glpi_networks (name)        TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_net_ent_id ON glpi_networks (entities_id) TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_equipments (partitionnee -> LOCAL) --------------------------
CREATE INDEX idx_equip_name ON glpi_equipments (name)           LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_equip_loc  ON glpi_equipments (locations_id)   LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_equip_ent  ON glpi_equipments (entities_id)    LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_equip_ip   ON glpi_equipments (ipaddresses_id) LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_equip_type ON glpi_equipments (itemtype)       LOCAL TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_computers (REFERENCE -> LOCAL herite du parent) -------------
-- idx_comp_serial supprime : couvert par uk_comp_serial (index unique)
CREATE INDEX idx_comp_usr_tch ON glpi_computers (users_id_tech)  LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_comp_usr     ON glpi_computers (users_id)       LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_comp_states  ON glpi_computers (states_id)      LOCAL TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_printers (REFERENCE -> LOCAL herite du parent) --------------
-- idx_print_serial supprime : couvert par uk_print_serial (index unique)
CREATE INDEX idx_print_usr_tch ON glpi_printers (users_id_tech)  LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_print_usr     ON glpi_printers (users_id)       LOCAL TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_print_states  ON glpi_printers (states_id)      LOCAL TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_ipaddresses -------------------------------------------------
CREATE INDEX idx_ip_name   ON glpi_ipaddresses (name)        TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_ip_net_id ON glpi_ipaddresses (networks_id) TABLESPACE TS_GLPI_INDX;

-- ---- Index glpi_profilerights -----------------------------------------------
CREATE INDEX idx_profright_name ON glpi_profilerights (name) TABLESPACE TS_GLPI_INDX;


-- =============================================================================
-- 4. CLES ETRANGERES
-- =============================================================================
-- fk_comp_inherit et fk_print_inherit sont declarees INLINE dans CREATE TABLE
-- (obligatoire pour PARTITION BY REFERENCE) -> pas de ALTER TABLE ici.

-- ---- glpi_equipments (table mere) -------------------------------------------
ALTER TABLE glpi_equipments
  ADD CONSTRAINT fk_equip_ent FOREIGN KEY (entities_id)
  REFERENCES glpi_entities(id);

ALTER TABLE glpi_equipments
  ADD CONSTRAINT fk_equip_loc FOREIGN KEY (locations_id)
  REFERENCES glpi_locations(id);

ALTER TABLE glpi_equipments
  ADD CONSTRAINT fk_equip_ip FOREIGN KEY (ipaddresses_id)
  REFERENCES glpi_ipaddresses(id);

-- ---- glpi_computers ---------------------------------------------------------
ALTER TABLE glpi_computers
  ADD CONSTRAINT fk_comp_user FOREIGN KEY (users_id)
  REFERENCES glpi_users(id);

ALTER TABLE glpi_computers
  ADD CONSTRAINT fk_comp_tech FOREIGN KEY (users_id_tech)
  REFERENCES glpi_users(id);

-- ---- glpi_printers ----------------------------------------------------------
ALTER TABLE glpi_printers
  ADD CONSTRAINT fk_print_user FOREIGN KEY (users_id)
  REFERENCES glpi_users(id);

ALTER TABLE glpi_printers
  ADD CONSTRAINT fk_print_tech FOREIGN KEY (users_id_tech)
  REFERENCES glpi_users(id);

-- ---- glpi_tickets -----------------------------------------------------------
ALTER TABLE glpi_tickets
  ADD CONSTRAINT fk_tick_equip FOREIGN KEY (equipment_id)
  REFERENCES glpi_equipments(id);

ALTER TABLE glpi_tickets
  ADD CONSTRAINT fk_tick_entity FOREIGN KEY (entities_id)
  REFERENCES glpi_entities(id);

ALTER TABLE glpi_tickets
  ADD CONSTRAINT fk_tick_location FOREIGN KEY (locations_id)
  REFERENCES glpi_locations(id);

ALTER TABLE glpi_tickets
  ADD CONSTRAINT fk_tick_user FOREIGN KEY (users_id)
  REFERENCES glpi_users(id);

-- ---- glpi_ipaddresses -------------------------------------------------------
ALTER TABLE glpi_ipaddresses
  ADD CONSTRAINT fk_ip_net FOREIGN KEY (networks_id)
  REFERENCES glpi_networks(id);

-- ---- glpi_networks ----------------------------------------------------------
ALTER TABLE glpi_networks
  ADD CONSTRAINT fk_net_ent FOREIGN KEY (entities_id)
  REFERENCES glpi_entities(id);

-- ---- glpi_locations ---------------------------------------------------------
-- fk_loc_parent supprimee (colonne locations_id supprimee)
ALTER TABLE glpi_locations
  ADD CONSTRAINT fk_loc_entity FOREIGN KEY (entities_id)
  REFERENCES glpi_entities(id);

-- ---- glpi_users -------------------------------------------------------------
ALTER TABLE glpi_users
  ADD CONSTRAINT fk_usr_entity FOREIGN KEY (entities_id)
  REFERENCES glpi_entities(id);

ALTER TABLE glpi_users
  ADD CONSTRAINT fk_usr_location FOREIGN KEY (locations_id)
  REFERENCES glpi_locations(id);

-- ---- glpi_profiles_users ----------------------------------------------------
ALTER TABLE glpi_profiles_users
  ADD CONSTRAINT fk_pu_user FOREIGN KEY (users_id)
  REFERENCES glpi_users(id);

ALTER TABLE glpi_profiles_users
  ADD CONSTRAINT fk_pu_profile FOREIGN KEY (profiles_id)
  REFERENCES glpi_profiles(id);

ALTER TABLE glpi_profiles_users
  ADD CONSTRAINT fk_pu_entity FOREIGN KEY (entities_id)
  REFERENCES glpi_entities(id);

-- ---- glpi_profilerights -----------------------------------------------------
ALTER TABLE glpi_profilerights
  ADD CONSTRAINT fk_profrights_profile FOREIGN KEY (profiles_id)
  REFERENCES glpi_profiles(id);


-- =============================================================================
-- 5. CONTRAINTES CHECK SUPPLEMENTAIRES
-- =============================================================================
-- chk_equip_itemtype et chk_equip_ent_id sont deja declares INLINE dans
-- le CREATE TABLE de glpi_equipments ci-dessus.
-- chk_ticket_ent et chk_tick_status idem pour glpi_tickets.

ALTER TABLE glpi_computers
  ADD CONSTRAINT chk_comp_states CHECK (states_id IN (1, 2, 3, 4));

ALTER TABLE glpi_printers
  ADD CONSTRAINT chk_print_states CHECK (states_id IN (1, 2, 3, 4));
