-- =============================================================================
-- GLPI CY Tech - Triggers d'integrite + Historique
-- A executer en GLPI_OWNER, apres OurBdd.sql.
-- =============================================================================


-- A. Table d'historique -------------------------------------------------------
DROP TABLE glpi_history CASCADE CONSTRAINTS;

CREATE TABLE glpi_history (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name  VARCHAR2(64)  NOT NULL,
  record_id   NUMBER        NOT NULL,
  action      VARCHAR2(10)  NOT NULL,
  changed_by  VARCHAR2(64)  DEFAULT USER NOT NULL,
  changed_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  old_data    CLOB,
  new_data    CLOB,
  CONSTRAINT chk_history_action CHECK (action IN ('INSERT','UPDATE','DELETE'))
)
TABLESPACE TS_GLPI_REF;

CREATE INDEX idx_hist_table_rec  ON glpi_history (table_name, record_id) TABLESPACE TS_GLPI_INDX;
CREATE INDEX idx_hist_changed_at ON glpi_history (changed_at)            TABLESPACE TS_GLPI_INDX;


-- B. Package d'audit (point d'ecriture unique dans glpi_history) --------------
CREATE OR REPLACE PACKAGE pkg_audit AS
  PROCEDURE log_change(
    p_table   IN VARCHAR2,
    p_record  IN NUMBER,
    p_action  IN VARCHAR2,
    p_old     IN CLOB DEFAULT NULL,
    p_new     IN CLOB DEFAULT NULL
  );
END pkg_audit;
/

CREATE OR REPLACE PACKAGE BODY pkg_audit AS
  PROCEDURE log_change(
    p_table   IN VARCHAR2,
    p_record  IN NUMBER,
    p_action  IN VARCHAR2,
    p_old     IN CLOB DEFAULT NULL,
    p_new     IN CLOB DEFAULT NULL
  ) IS
  BEGIN
    INSERT INTO glpi_history (table_name, record_id, action, old_data, new_data)
    VALUES (p_table, p_record, p_action, p_old, p_new);
  END log_change;
END pkg_audit;
/


-- C. Triggers d'integrite -----------------------------------------------------

-- Interdit changer de campus pour une ligne de lieu : deplacer un lieu = INSERT
-- nouveau cote destinataire + migration des enfants ou autre stratégie fonctionnelle.
CREATE OR REPLACE TRIGGER tr_loc_no_chg_entity
BEFORE UPDATE OF entities_id ON glpi_locations
FOR EACH ROW
BEGIN
  IF :OLD.entities_id <> :NEW.entities_id THEN
    RAISE_APPLICATION_ERROR(-20005,
      'Changement interdit pour glpi_locations.entities_id (ancien=' || :OLD.entities_id ||
      ', nouveau=' || :NEW.entities_id || '). Migrer avec un script dedie.');
  END IF;
END;
/

-- Un ticket et son equipement doivent etre du meme site.
CREATE OR REPLACE TRIGGER tr_ticket_equip_entity
BEFORE INSERT OR UPDATE OF equipment_id, entities_id ON glpi_tickets
FOR EACH ROW
DECLARE
  v_equip_ent NUMBER;
BEGIN
  IF :NEW.equipment_id IS NOT NULL THEN
    SELECT entities_id INTO v_equip_ent
      FROM glpi_equipments
     WHERE id = :NEW.equipment_id;

    IF v_equip_ent <> :NEW.entities_id THEN
      RAISE_APPLICATION_ERROR(-20002,
        'Ticket entities_id=' || :NEW.entities_id ||
        ' incoherent avec equipment entities_id=' || v_equip_ent);
    END IF;
  END IF;
END;
/

-- Si un ticket refere un lieu physique, ce lieu doit appartenir au meme campus que le ticket.
CREATE OR REPLACE TRIGGER tr_ticket_loc_entity
BEFORE INSERT OR UPDATE OF locations_id, entities_id ON glpi_tickets
FOR EACH ROW
DECLARE
  v_loc_ent NUMBER;
BEGIN
  IF :NEW.locations_id IS NOT NULL THEN
    BEGIN
      SELECT entities_id INTO v_loc_ent
        FROM glpi_locations
       WHERE id = :NEW.locations_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20006,
          'Lieu inexistant pour le ticket : locations_id=' || :NEW.locations_id);
    END;
    IF v_loc_ent <> :NEW.entities_id THEN
      RAISE_APPLICATION_ERROR(-20008,
        'Ticket entities_id=' || :NEW.entities_id ||
        ' incoherent avec glpi_locations.entities_id=' || v_loc_ent ||
        ' (locations_id=' || :NEW.locations_id || ')');
    END IF;
  END IF;
END;
/

-- Un equipement ne peut pas etre rattache (FK) a un lieu d'un autre campus que le sien.
CREATE OR REPLACE TRIGGER tr_equip_loc_entity
BEFORE INSERT OR UPDATE OF locations_id, entities_id ON glpi_equipments
FOR EACH ROW
DECLARE
  v_loc_ent NUMBER;
BEGIN
  IF :NEW.locations_id IS NOT NULL THEN
    BEGIN
      SELECT entities_id INTO v_loc_ent
        FROM glpi_locations
       WHERE id = :NEW.locations_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20009,
          'Lieu inexistant pour l equipement : locations_id=' || :NEW.locations_id);
    END;
    IF v_loc_ent <> :NEW.entities_id THEN
      RAISE_APPLICATION_ERROR(-20004,
        'Equipement entities_id=' || :NEW.entities_id ||
        ' incoherent avec glpi_locations.entities_id=' || v_loc_ent ||
        ' (locations_id=' || :NEW.locations_id || ')');
    END IF;
  END IF;
END;
/

-- Interdit le changement de site (forcerait une migration entre partitions).
CREATE OR REPLACE TRIGGER tr_equip_no_chg_entity
BEFORE UPDATE OF entities_id ON glpi_equipments
FOR EACH ROW
BEGIN
  IF :OLD.entities_id <> :NEW.entities_id THEN
    RAISE_APPLICATION_ERROR(-20003,
      'Changement de entities_id interdit (ancien=' || :OLD.entities_id ||
      ', nouveau=' || :NEW.entities_id || ')');
  END IF;
END;
/


-- D. Triggers d'historique ----------------------------------------------------

-- Audit du parc materiel.
CREATE OR REPLACE TRIGGER tr_hist_equipments
AFTER INSERT OR UPDATE OR DELETE ON glpi_equipments
FOR EACH ROW
DECLARE
  v_old CLOB;
  v_new CLOB;
  v_id  NUMBER;
  v_act VARCHAR2(10);
BEGIN
  IF INSERTING THEN
    v_act := 'INSERT'; v_id := :NEW.id;
  ELSIF UPDATING THEN
    v_act := 'UPDATE'; v_id := :NEW.id;
  ELSE
    v_act := 'DELETE'; v_id := :OLD.id;
  END IF;

  IF NOT INSERTING THEN
    v_old := 'id='        || :OLD.id        ||
             ';name='     || :OLD.name      ||
             ';itemtype=' || :OLD.itemtype  ||
             ';ent='      || :OLD.entities_id ||
             ';loc='      || :OLD.locations_id ||
             ';ip='       || :OLD.ipaddresses_id;
  END IF;
  IF NOT DELETING THEN
    v_new := 'id='        || :NEW.id        ||
             ';name='     || :NEW.name      ||
             ';itemtype=' || :NEW.itemtype  ||
             ';ent='      || :NEW.entities_id ||
             ';loc='      || :NEW.locations_id ||
             ';ip='       || :NEW.ipaddresses_id;
  END IF;

  pkg_audit.log_change('glpi_equipments', v_id, v_act, v_old, v_new);
END;
/

-- Audit des arborescences lieux par campus.
CREATE OR REPLACE TRIGGER tr_hist_locations
AFTER INSERT OR UPDATE OR DELETE ON glpi_locations
FOR EACH ROW
DECLARE
  v_old CLOB;
  v_new CLOB;
  v_id  NUMBER;
  v_act VARCHAR2(10);
BEGIN
  IF INSERTING THEN
    v_act := 'INSERT'; v_id := :NEW.id;
  ELSIF UPDATING THEN
    v_act := 'UPDATE'; v_id := :NEW.id;
  ELSE
    v_act := 'DELETE'; v_id := :OLD.id;
  END IF;

  IF NOT INSERTING THEN
    v_old := 'id='   || :OLD.id          ||
             ';name=' || :OLD.name        ||
             ';lvl='  || :OLD.lvl         ||
             ';ent='  || :OLD.entities_id;
  END IF;
  IF NOT DELETING THEN
    v_new := 'id='   || :NEW.id          ||
             ';name=' || :NEW.name        ||
             ';lvl='  || :NEW.lvl         ||
             ';ent='  || :NEW.entities_id;
  END IF;

  pkg_audit.log_change('glpi_locations', v_id, v_act, v_old, v_new);
END;
/

-- Audit du cycle de vie des tickets.
CREATE OR REPLACE TRIGGER tr_hist_tickets
AFTER INSERT OR UPDATE OR DELETE ON glpi_tickets
FOR EACH ROW
DECLARE
  v_old CLOB;
  v_new CLOB;
  v_id  NUMBER;
  v_act VARCHAR2(10);
BEGIN
  IF INSERTING THEN
    v_act := 'INSERT'; v_id := :NEW.id;
  ELSIF UPDATING THEN
    v_act := 'UPDATE'; v_id := :NEW.id;
  ELSE
    v_act := 'DELETE'; v_id := :OLD.id;
  END IF;

  IF NOT INSERTING THEN
    v_old := 'id='      || :OLD.id ||
             ';name='   || :OLD.name ||
             ';status=' || :OLD.status ||
             ';ent='    || :OLD.entities_id ||
             ';loc='    || NVL(TO_CHAR(:OLD.locations_id), 'NULL') ||
             ';equip='  || NVL(TO_CHAR(:OLD.equipment_id), 'NULL') ||
             ';user='   || NVL(TO_CHAR(:OLD.users_id), 'NULL');
  END IF;
  IF NOT DELETING THEN
    v_new := 'id='      || :NEW.id ||
             ';name='   || :NEW.name ||
             ';status=' || :NEW.status ||
             ';ent='    || :NEW.entities_id ||
             ';loc='    || NVL(TO_CHAR(:NEW.locations_id), 'NULL') ||
             ';equip='  || NVL(TO_CHAR(:NEW.equipment_id), 'NULL') ||
             ';user='   || NVL(TO_CHAR(:NEW.users_id), 'NULL');
  END IF;

  pkg_audit.log_change('glpi_tickets', v_id, v_act, v_old, v_new);
END;
/


-- E. Grants -------------------------------------------------------------------
GRANT SELECT ON glpi_history TO R_GLPI_READ;
